// GENERATED by tools/gen_braille_header.py from data/braille_map.json -- DO NOT EDIT
// standard: PLACEHOLDER_BHARATI   verified: False
// !! GENERATED FROM AN UNVERIFIED PLACEHOLDER MAPPING.
// !! Swap in the verified Bangladesh chart before real learners use this.

#ifndef BRAILLE_MAP_H
#define BRAILLE_MAP_H

#include <stdint.h>

#define BRAILLE_LETTER_COUNT 50
#define BRAILLE_MAP_VERIFIED 0
#define BRAILLE_VOWEL_COUNT 11

// Bit i set => dot i+1 is raised.  bit0=dot1 bit1=dot2 bit2=dot3
//                                  bit3=dot4 bit4=dot5 bit5=dot6
// Index is the letter id, which matches feature 0 (char_id) exactly.
static const uint8_t BRAILLE_PATTERN[BRAILLE_LETTER_COUNT] = {
  0x01,  //  0  অ  a              dots 1
  0x1C,  //  1  আ  aa             dots 3-4-5
  0x0A,  //  2  ই  i              dots 2-4
  0x14,  //  3  ঈ  ii             dots 3-5
  0x25,  //  4  উ  u              dots 1-3-6
  0x33,  //  5  ঊ  uu             dots 1-2-5-6
  0x16,  //  6  ঋ  ri             dots 2-3-5
  0x11,  //  7  এ  e              dots 1-5
  0x0C,  //  8  ঐ  oi             dots 3-4
  0x15,  //  9  ও  o              dots 1-3-5
  0x2A,  // 10  ঔ  ou             dots 2-4-6
  0x05,  // 11  ক  ka             dots 1-3
  0x28,  // 12  খ  kha            dots 4-6
  0x1B,  // 13  গ  ga             dots 1-2-4-5
  0x23,  // 14  ঘ  gha            dots 1-2-6
  0x2C,  // 15  ঙ  uma            dots 3-4-6
  0x09,  // 16  চ  cha            dots 1-4
  0x21,  // 17  ছ  chha           dots 1-6
  0x1A,  // 18  জ  ja             dots 2-4-5
  0x34,  // 19  ঝ  jha            dots 3-5-6
  0x12,  // 20  ঞ  nia            dots 2-5
  0x3E,  // 21  ট  tta            dots 2-3-4-5-6
  0x3A,  // 22  ঠ  ttha           dots 2-4-5-6
  0x2B,  // 23  ড  dda            dots 1-2-4-6
  0x3F,  // 24  ঢ  ddha           dots 1-2-3-4-5-6
  0x3C,  // 25  ণ  nna            dots 3-4-5-6
  0x1E,  // 26  ত  ta             dots 2-3-4-5
  0x39,  // 27  থ  tha            dots 1-4-5-6
  0x19,  // 28  দ  da             dots 1-4-5
  0x2E,  // 29  ধ  dha            dots 2-3-4-6
  0x1D,  // 30  ন  na             dots 1-3-4-5
  0x0F,  // 31  প  pa             dots 1-2-3-4
  0x0B,  // 32  ফ  pha            dots 1-2-4
  0x03,  // 33  ব  ba             dots 1-2
  0x18,  // 34  ভ  bha            dots 4-5
  0x0D,  // 35  ম  ma             dots 1-3-4
  0x3D,  // 36  য  ya             dots 1-3-4-5-6
  0x17,  // 37  র  ra             dots 1-2-3-5
  0x07,  // 38  ল  la             dots 1-2-3
  0x29,  // 39  শ  sha            dots 1-4-6
  0x2F,  // 40  ষ  ssa            dots 1-2-3-4-6
  0x0E,  // 41  স  sa             dots 2-3-4
  0x13,  // 42  হ  ha             dots 1-2-5
  0x3B,  // 43  ড়  rra            dots 1-2-4-5-6
  0x37,  // 44  ঢ়  rha            dots 1-2-3-5-6
  0x36,  // 45  য়  yya            dots 2-3-5-6
  0x26,  // 46  ৎ  khanda_ta      dots 2-3-6
  0x30,  // 47  ং  anushar        dots 5-6
  0x06,  // 48  ঃ  bisharga       dots 2-3
  0x08,  // 49  ঁ  chandrabindu   dots 4
};

// Kept in PROGMEM-free plain flash; only used for SD-card log lines.
static const char *const BRAILLE_NAME[BRAILLE_LETTER_COUNT] = {
  "a",
  "aa",
  "i",
  "ii",
  "u",
  "uu",
  "ri",
  "e",
  "oi",
  "o",
  "ou",
  "ka",
  "kha",
  "ga",
  "gha",
  "uma",
  "cha",
  "chha",
  "ja",
  "jha",
  "nia",
  "tta",
  "ttha",
  "dda",
  "ddha",
  "nna",
  "ta",
  "tha",
  "da",
  "dha",
  "na",
  "pa",
  "pha",
  "ba",
  "bha",
  "ma",
  "ya",
  "ra",
  "la",
  "sha",
  "ssa",
  "sa",
  "ha",
  "rra",
  "rha",
  "yya",
  "khanda_ta",
  "anushar",
  "bisharga",
  "chandrabindu"
};

static const char *const BRAILLE_ROMAN[BRAILLE_LETTER_COUNT] = {
  "o",
  "a",
  "i",
  "ee",
  "u",
  "oo",
  "ri",
  "e",
  "oi",
  "o",
  "ou",
  "ka",
  "kha",
  "ga",
  "gha",
  "nga",
  "cha",
  "chha",
  "ja",
  "jha",
  "nya",
  "ta",
  "tha",
  "da",
  "dha",
  "na",
  "ta",
  "tha",
  "da",
  "dha",
  "na",
  "pa",
  "pha",
  "ba",
  "bha",
  "ma",
  "ja",
  "ra",
  "la",
  "sha",
  "sha",
  "sa",
  "ha",
  "ra",
  "rha",
  "ya",
  "t",
  "ng",
  "h",
  "n"
};

// DFPlayer track number for letter id (files are /mp3/0001.mp3 .. /mp3/0050.mp3)
static inline uint16_t braille_track(uint8_t letter_id) {
  return (uint16_t)letter_id + 1;
}

static inline uint8_t braille_dot_count(uint8_t mask) {
  uint8_t c = 0;
  for (uint8_t i = 0; i < 6; i++) if (mask & (1 << i)) c++;
  return c;
}

#endif  // BRAILLE_MAP_H
