// GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT
// spec version: 1
#ifndef RULE_ENGINE_H
#define RULE_ENGINE_H

#define FEATURE_COUNT 14

typedef enum {
  TA_REPEAT = 0,
  TA_HINT = 1,
  TA_NORMAL_PRACTICE = 2,
  TA_INCREASE_DIFFICULTY = 3,
  TA_REVIEW_PREVIOUS = 4,
  TA_WORD_PRACTICE = 5
} TeachingAction;

typedef enum {
  CS_CONFIDENT = 0,
  CS_HESITANT = 1,
  CS_GUESSING = 2
} ConfidenceState;

static const char *TEACHING_ACTION_NAMES[] = { "REPEAT", "HINT", "NORMAL_PRACTICE", "INCREASE_DIFFICULTY", "REVIEW_PREVIOUS", "WORD_PRACTICE" };
static const char *CONFIDENCE_STATE_NAMES[] = { "CONFIDENT", "HESITANT", "GUESSING" };

// All fields are the state AFTER the current attempt has been scored.
// current_streak > 0 => that attempt was CORRECT; wrong_streak > 0 => WRONG.
typedef struct {
  double char_id;
  double response_time;
  double press_duration;
  double retry_count;
  double prev_accuracy;
  double prev_mastery;
  double hint_count;
  double session_number;
  double difficulty_level;
  double time_since_last_practice;
  double prev_confidence;
  double current_streak;
  double wrong_streak;
  double prev_mistakes;
} Features;

static const double FEATURE_MIN[FEATURE_COUNT] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
static const double FEATURE_MAX[FEATURE_COUNT] = { 49.0, 15000.0, 2000.0, 10.0, 1.0, 1.0, 10.0, 50.0, 5.0, 604800.0, 2.0, 20.0, 20.0, 50.0 };

// Canonical order. Must match FEATURE_INDEX in web/rule_engine.js.
static inline void features_to_vector(const Features *f, double *v) {
  v[0] = f->char_id;
  v[1] = f->response_time;
  v[2] = f->press_duration;
  v[3] = f->retry_count;
  v[4] = f->prev_accuracy;
  v[5] = f->prev_mastery;
  v[6] = f->hint_count;
  v[7] = f->session_number;
  v[8] = f->difficulty_level;
  v[9] = f->time_since_last_practice;
  v[10] = f->prev_confidence;
  v[11] = f->current_streak;
  v[12] = f->wrong_streak;
  v[13] = f->prev_mistakes;
}

// Fixed min-max scaling with clamping. Ranges are from the spec, not the
// dataset, so retraining can never desync this from the model.
static inline void normalize_features(const Features *f, float *out) {
  double v[FEATURE_COUNT];
  features_to_vector(f, v);
  for (int i = 0; i < FEATURE_COUNT; i++) {
    double n = (v[i] - FEATURE_MIN[i]) / (FEATURE_MAX[i] - FEATURE_MIN[i]);
    if (n < 0.0) n = 0.0;
    if (n > 1.0) n = 1.0;
    out[i] = (float)n;
  }
}

static inline TeachingAction evaluate_teaching_action(const Features *f) {
  // ta_review_on_repeated_failure: Three wrong in a row on one character means the learner is stuck; go back rather than grind.
  if (f->wrong_streak >= 3.0) return TA_REVIEW_PREVIOUS;

  // ta_hint_after_retries: Struggling but no hint given yet.
  if (f->retry_count >= 2.0 && f->hint_count == 0.0) return TA_HINT;

  // ta_repeat_on_wrong: Attempt was wrong (see correctness_is_derivable) but not yet stuck.
  if (f->wrong_streak >= 1.0) return TA_REPEAT;

  // ta_word_practice_on_mastery: Character is solid; move to word-level use.
  if (f->prev_mastery >= 0.85 && f->current_streak >= 5.0 && f->prev_accuracy >= 0.8) return TA_WORD_PRACTICE;

  // ta_increase_difficulty: Doing well; raise the tier.
  if (f->prev_mastery >= 0.7 && f->current_streak >= 3.0) return TA_INCREASE_DIFFICULTY;

  // ta_review_after_long_gap: Weak character not seen for a day; refresh it.
  if (f->time_since_last_practice >= 86400.0 && f->prev_mastery < 0.5) return TA_REVIEW_PREVIOUS;

  // ta_default: Default.
  return TA_NORMAL_PRACTICE;
}

static inline ConfidenceState evaluate_confidence(const Features *f) {
  // cs_guessing: Many retries or a very long pause both read as guessing.
  if (f->retry_count >= 2.0 || f->response_time >= 6000.0) return CS_GUESSING;

  // cs_confident: Fast, clean, first-try, correct.
  if (f->response_time <= 2500.0 && f->retry_count == 0.0 && f->wrong_streak == 0.0 && f->press_duration <= 400.0) return CS_CONFIDENT;

  // cs_default: Default.
  return CS_HESITANT;
}

// Must match updateMastery() in web/rule_engine.js exactly.
static inline double update_mastery(double mastery, int correct) {
  return correct ? mastery + 0.25 * (1.0 - mastery)
                 : mastery - 0.35 * mastery;
}

#define MASTERY_INITIAL 0.0
#define SESSION_IDLE_TIMEOUT_S 900
#define SESSION_TARGET_ATTEMPTS 20

#endif  // RULE_ENGINE_H
