// GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT
// spec version: 2
#ifndef RULE_ENGINE_H
#define RULE_ENGINE_H

#define SPEC_VERSION 2
#define ALL_FEATURE_COUNT 14
#define FEATURE_COUNT 4

typedef enum {
  TA_REPEAT = 0,
  TA_HINT = 1,
  TA_NORMAL_PRACTICE = 2
} TeachingAction;

typedef enum {
  CS_CONFIDENT = 0,
  CS_HESITANT = 1,
  CS_GUESSING = 2
} ConfidenceState;

// Only referenced by the SD-card log path, so a build that does not log would
// warn on them; the attribute keeps -Wall -Wextra clean either way.
__attribute__((unused)) static const char *TEACHING_ACTION_NAMES[] = { "REPEAT", "HINT", "NORMAL_PRACTICE" };
__attribute__((unused)) static const char *CONFIDENCE_STATE_NAMES[] = { "CONFIDENT", "HESITANT", "GUESSING" };

// All fields are the state AFTER the current attempt has been scored.
// current_streak > 0 => that attempt was CORRECT; wrong_streak > 0 => WRONG.
// This struct holds ALL 14 logged features (the CSV/DB schema), not
// just the ones fed to the model -- see FEATURE_COUNT vs ALL_FEATURE_COUNT.
typedef struct {
  double char_id;
  double response_time;
  double press_duration;
  double retry_count;
  double prev_accuracy;
  double prev_mastery;
  double hint_count;
  double session_number;
  double difficulty_level;
  double time_since_last_practice;
  double prev_confidence;
  double current_streak;
  double wrong_streak;
  double prev_mistakes;
} Features;

// Min/max for ALL 14 logged features, in spec order (index i here
// matches feature i in spec/engine_spec.json). Use this array (not the
// model-only FEATURE_MIN/MAX below) when a specific feature's raw range is
// needed regardless of whether it feeds the model -- e.g. the "never
// practiced" sentinel in learner_state.h.
__attribute__((unused)) static const double ALL_FEATURE_MIN[ALL_FEATURE_COUNT] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
__attribute__((unused)) static const double ALL_FEATURE_MAX[ALL_FEATURE_COUNT] = { 49.0, 15000.0, 2000.0, 10.0, 1.0, 1.0, 10.0, 50.0, 5.0, 604800.0, 2.0, 20.0, 20.0, 50.0 };

// Model input only (model_input=true in the spec). Must match FEATURE_INDEX
// in web/rule_engine.js.
static const double FEATURE_MIN[FEATURE_COUNT] = { 0.0, 0.0, 0.0, 0.0 };
static const double FEATURE_MAX[FEATURE_COUNT] = { 15000.0, 2000.0, 10.0, 20.0 };

static inline void features_to_vector(const Features *f, double *v) {
  v[0] = f->response_time;
  v[1] = f->press_duration;
  v[2] = f->retry_count;
  v[3] = f->wrong_streak;
}

// Fixed min-max scaling with clamping. Ranges are from the spec, not the
// dataset, so retraining can never desync this from the model.
static inline void normalize_features(const Features *f, float *out) {
  double v[FEATURE_COUNT];
  features_to_vector(f, v);
  for (int i = 0; i < FEATURE_COUNT; i++) {
    double n = (v[i] - FEATURE_MIN[i]) / (FEATURE_MAX[i] - FEATURE_MIN[i]);
    if (n < 0.0) n = 0.0;
    if (n > 1.0) n = 1.0;
    out[i] = (float)n;
  }
}

static inline TeachingAction evaluate_teaching_action(const Features *f) {
  // ta_repeat_on_first_wrong: First wrong attempt on this prompt -- just try again, no help yet.
  if (f->wrong_streak >= 1.0 && f->retry_count == 0.0) return TA_REPEAT;

  // ta_hint_while_stuck: Still wrong after at least one retry on this prompt (retry_count>=1, since ta_repeat_on_first_wrong already caught retry_count==0). Keep helping on THIS character every subsequent wrong try, uncapped, rather than escalating to a different one -- REVIEW_PREVIOUS was removed because abandoning the current letter mid-struggle teaches nothing about the letter the learner actually needs.
  if (f->wrong_streak >= 1.0) return TA_HINT;

  // ta_default: wrong_streak==0, so the attempt just scored was correct -- move on normally.
  return TA_NORMAL_PRACTICE;
}

static inline ConfidenceState evaluate_confidence(const Features *f) {
  // cs_guessing: Many retries or a very long pause both read as guessing.
  if (f->retry_count >= 2.0 || f->response_time >= 6000.0) return CS_GUESSING;

  // cs_confident: Fast, clean, first-try, correct.
  if (f->response_time <= 2500.0 && f->retry_count == 0.0 && f->wrong_streak == 0.0 && f->press_duration <= 400.0) return CS_CONFIDENT;

  // cs_default: Default.
  return CS_HESITANT;
}

// Must match updateMastery() in web/rule_engine.js exactly.
static inline double update_mastery(double mastery, int correct) {
  return correct ? mastery + 0.25 * (1.0 - mastery)
                 : mastery - 0.35 * mastery;
}

#define MASTERY_INITIAL 0.0
#define SESSION_IDLE_TIMEOUT_S 900
#define SESSION_TARGET_ATTEMPTS 20

#endif  // RULE_ENGINE_H
