#!/usr/bin/env python3
"""Generate the rule engine for BOTH web and firmware from spec/engine_spec.json.

This exists to kill one specific bug class: the web app and the ESP32 computing
features or rules slightly differently, so a model trained on web-collected data
misbehaves on hardware. Neither output file is ever hand-written.

    python3 tools/gen_engine.py      # writes both files
    python3 tools/test_parity.py     # proves they agree

Note on types: the C side uses `double`, not `float`. The rule engine runs once
per attempt, so the software-emulated double cost on ESP32 is irrelevant, and it
removes float-vs-double rounding as a source of JS/C disagreement.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "spec" / "engine_spec.json"
JS_OUT = ROOT / "web" / "rule_engine.js"
H_OUT = ROOT / "firmware" / "braille_tutor" / "rule_engine.h"
PY_OUT = ROOT / "tools" / "rule_engine_gen.py"

BANNER = "GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT"


def fmt_num(v):
    """Emit a numeric literal identically in JS and C."""
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return f"{v}.0"
    return repr(float(v))


def cond_expr(cond, accessor):
    op = cond["op"]
    if op == "==":
        op = "=="
    return f"{accessor(cond['feature'])} {op} {fmt_num(cond['value'])}"


def build_rule_block(rules, accessor, enum_prefix, indent, comment_tok):
    """Render an ordered first-match-wins rule chain. Same shape in JS and C."""
    lines = []
    pad = " " * indent
    for rule in rules:
        conds = rule["conditions"]
        joiner = " && " if rule["logic"] == "AND" else " || "
        if not conds:
            lines.append(f"{pad}{comment_tok} {rule['id']}: {rule['rationale']}")
            lines.append(f"{pad}return {enum_prefix}{rule['result']};")
        else:
            expr = joiner.join(cond_expr(c, accessor) for c in conds)
            lines.append(f"{pad}{comment_tok} {rule['id']}: {rule['rationale']}")
            lines.append(f"{pad}if ({expr}) return {enum_prefix}{rule['result']};")
        lines.append("")
    return "\n".join(lines).rstrip()


def gen_js(spec):
    feats = spec["features"]
    ta = spec["outputs"]["teaching_action"]["classes"]
    cs = spec["outputs"]["confidence_state"]["classes"]
    mu = spec["mastery_update"]

    acc = lambda name: f"f.{name}"

    idx_lines = "\n".join(
        f"  {f['name']}: {f['index']}," for f in feats
    )
    norm_lines = "\n".join(
        f"  {{ name: '{f['name']}', min: {fmt_num(f['min'])}, max: {fmt_num(f['max'])} }},"
        for f in feats
    )
    ta_enum = "\n".join(f"  {n}: {i}," for i, n in enumerate(ta))
    cs_enum = "\n".join(f"  {n}: {i}," for i, n in enumerate(cs))

    return f"""// {BANNER}
// spec version: {spec['version']}

export const SPEC_VERSION = {spec['version']};

export const TEACHING_ACTION = {{
{ta_enum}
}};
export const TEACHING_ACTION_NAMES = {json.dumps(ta)};

export const CONFIDENCE_STATE = {{
{cs_enum}
}};
export const CONFIDENCE_STATE_NAMES = {json.dumps(cs)};

// Canonical feature order. The model input vector MUST be built in this order.
export const FEATURE_INDEX = {{
{idx_lines}
}};

export const FEATURE_RANGES = [
{norm_lines}
];

export const FEATURE_COUNT = {len(feats)};

/**
 * Fixed min-max scaling with clamping. Ranges come from the spec, NOT from the
 * dataset, so retraining on more data can never shift what the ESP32 computes.
 */
export function normalizeFeatures(f) {{
  const out = new Float32Array(FEATURE_COUNT);
  for (let i = 0; i < FEATURE_COUNT; i++) {{
    const r = FEATURE_RANGES[i];
    const raw = f[r.name];
    if (raw === undefined || raw === null || Number.isNaN(raw)) {{
      throw new Error('normalizeFeatures: missing feature ' + r.name);
    }}
    let v = (raw - r.min) / (r.max - r.min);
    if (v < 0) v = 0;
    if (v > 1) v = 1;
    out[i] = v;
  }}
  return out;
}}

/** Ordered raw feature vector, for CSV logging. */
export function featureVector(f) {{
  return FEATURE_RANGES.map((r) => f[r.name]);
}}

export function evaluateTeachingAction(f) {{
{build_rule_block(spec['teaching_action_rules'], acc, 'TEACHING_ACTION.', 2, '//')}
}}

export function evaluateConfidence(f) {{
{build_rule_block(spec['confidence_rules'], acc, 'CONFIDENCE_STATE.', 2, '//')}
}}

/** EMA mastery update. Must match firmware and gen_synthetic.py exactly. */
export function updateMastery(mastery, correct) {{
  return correct
    ? mastery + {fmt_num(mu['alpha_correct'])} * (1.0 - mastery)
    : mastery - {fmt_num(mu['alpha_wrong'])} * mastery;
}}

export const MASTERY_INITIAL = {fmt_num(mu['initial'])};
export const SESSION_IDLE_TIMEOUT_S = {spec['session']['idle_timeout_s']};
export const SESSION_TARGET_ATTEMPTS = {spec['session']['target_attempts']};
"""


def gen_h(spec):
    feats = spec["features"]
    ta = spec["outputs"]["teaching_action"]["classes"]
    cs = spec["outputs"]["confidence_state"]["classes"]
    mu = spec["mastery_update"]

    acc = lambda name: f"f->{name}"

    struct_lines = "\n".join(f"  double {f['name']};" for f in feats)
    ta_enum = ",\n".join(f"  TA_{n} = {i}" for i, n in enumerate(ta))
    cs_enum = ",\n".join(f"  CS_{n} = {i}" for i, n in enumerate(cs))
    min_arr = ", ".join(fmt_num(f["min"]) for f in feats)
    max_arr = ", ".join(fmt_num(f["max"]) for f in feats)
    order_lines = "\n".join(
        f"  v[{f['index']}] = f->{f['name']};" for f in feats
    )
    ta_names = ", ".join(f'"{n}"' for n in ta)
    cs_names = ", ".join(f'"{n}"' for n in cs)

    return f"""// {BANNER}
// spec version: {spec['version']}
#ifndef RULE_ENGINE_H
#define RULE_ENGINE_H

#define SPEC_VERSION {spec['version']}
#define FEATURE_COUNT {len(feats)}

typedef enum {{
{ta_enum}
}} TeachingAction;

typedef enum {{
{cs_enum}
}} ConfidenceState;

// Only referenced by the SD-card log path, so a build that does not log would
// warn on them; the attribute keeps -Wall -Wextra clean either way.
__attribute__((unused)) static const char *TEACHING_ACTION_NAMES[] = {{ {ta_names} }};
__attribute__((unused)) static const char *CONFIDENCE_STATE_NAMES[] = {{ {cs_names} }};

// All fields are the state AFTER the current attempt has been scored.
// current_streak > 0 => that attempt was CORRECT; wrong_streak > 0 => WRONG.
typedef struct {{
{struct_lines}
}} Features;

static const double FEATURE_MIN[FEATURE_COUNT] = {{ {min_arr} }};
static const double FEATURE_MAX[FEATURE_COUNT] = {{ {max_arr} }};

// Canonical order. Must match FEATURE_INDEX in web/rule_engine.js.
static inline void features_to_vector(const Features *f, double *v) {{
{order_lines}
}}

// Fixed min-max scaling with clamping. Ranges are from the spec, not the
// dataset, so retraining can never desync this from the model.
static inline void normalize_features(const Features *f, float *out) {{
  double v[FEATURE_COUNT];
  features_to_vector(f, v);
  for (int i = 0; i < FEATURE_COUNT; i++) {{
    double n = (v[i] - FEATURE_MIN[i]) / (FEATURE_MAX[i] - FEATURE_MIN[i]);
    if (n < 0.0) n = 0.0;
    if (n > 1.0) n = 1.0;
    out[i] = (float)n;
  }}
}}

static inline TeachingAction evaluate_teaching_action(const Features *f) {{
{build_rule_block(spec['teaching_action_rules'], acc, 'TA_', 2, '//')}
}}

static inline ConfidenceState evaluate_confidence(const Features *f) {{
{build_rule_block(spec['confidence_rules'], acc, 'CS_', 2, '//')}
}}

// Must match updateMastery() in web/rule_engine.js exactly.
static inline double update_mastery(double mastery, int correct) {{
  return correct ? mastery + {fmt_num(mu['alpha_correct'])} * (1.0 - mastery)
                 : mastery - {fmt_num(mu['alpha_wrong'])} * mastery;
}}

#define MASTERY_INITIAL {fmt_num(mu['initial'])}
#define SESSION_IDLE_TIMEOUT_S {spec['session']['idle_timeout_s']}
#define SESSION_TARGET_ATTEMPTS {spec['session']['target_attempts']}

#endif  // RULE_ENGINE_H
"""


def gen_py(spec):
    """Python engine, used by gen_synthetic.py and train.py.

    Without this, synthetic rows would be labelled by a hand-written Python
    copy of the rules and could drift from what the web app actually logged --
    poisoning 60% of the dataset in a way that is very hard to notice.
    """
    feats = spec["features"]
    ta = spec["outputs"]["teaching_action"]["classes"]
    cs = spec["outputs"]["confidence_state"]["classes"]
    mu = spec["mastery_update"]

    acc = lambda name: f"f['{name}']"

    ta_enum = "\n".join(f"    {n} = {i}" for i, n in enumerate(ta))
    cs_enum = "\n".join(f"    {n} = {i}" for i, n in enumerate(cs))
    ranges = "\n".join(
        f"    ({f['index']}, '{f['name']}', {fmt_num(f['min'])}, {fmt_num(f['max'])}),"
        for f in feats
    )

    body_ta = build_rule_block(spec["teaching_action_rules"], acc, "TeachingAction.", 4, "#")
    body_cs = build_rule_block(spec["confidence_rules"], acc, "ConfidenceState.", 4, "#")
    body_ta = body_ta.replace("if (", "if ").replace(") return", ": return")
    body_cs = body_cs.replace("if (", "if ").replace(") return", ": return")
    body_ta = body_ta.replace("&&", "and").replace("||", "or").replace(";", "")
    body_cs = body_cs.replace("&&", "and").replace("||", "or").replace(";", "")

    return f'''# {BANNER}
# spec version: {spec['version']}
"""Python mirror of the rule engine. Imported by gen_synthetic.py and train.py."""
from enum import IntEnum

SPEC_VERSION = {spec['version']}


class TeachingAction(IntEnum):
{ta_enum}


class ConfidenceState(IntEnum):
{cs_enum}


TEACHING_ACTION_NAMES = {json.dumps(ta)}
CONFIDENCE_STATE_NAMES = {json.dumps(cs)}

# (index, name, min, max) in canonical model-input order
FEATURE_RANGES = [
{ranges}
]
FEATURE_NAMES = [r[1] for r in FEATURE_RANGES]
FEATURE_COUNT = {len(feats)}


def normalize_features(f):
    """Fixed min-max scaling with clamping. Ranges are from the spec, not the
    dataset, so retraining can never desync this from the deployed model."""
    out = []
    for _, name, lo, hi in FEATURE_RANGES:
        v = (float(f[name]) - lo) / (hi - lo)
        out.append(0.0 if v < 0.0 else 1.0 if v > 1.0 else v)
    return out


def feature_vector(f):
    return [float(f[name]) for _, name, _, _ in FEATURE_RANGES]


def evaluate_teaching_action(f):
{body_ta}


def evaluate_confidence(f):
{body_cs}


def update_mastery(mastery, correct):
    return (mastery + {fmt_num(mu['alpha_correct'])} * (1.0 - mastery)) if correct \\
        else (mastery - {fmt_num(mu['alpha_wrong'])} * mastery)


MASTERY_INITIAL = {fmt_num(mu['initial'])}
SESSION_IDLE_TIMEOUT_S = {spec['session']['idle_timeout_s']}
SESSION_TARGET_ATTEMPTS = {spec['session']['target_attempts']}
'''


def main():
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    H_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.write_text(gen_js(spec), encoding="utf-8")
    H_OUT.write_text(gen_h(spec), encoding="utf-8")
    PY_OUT.write_text(gen_py(spec), encoding="utf-8")
    print(f"wrote {JS_OUT.relative_to(ROOT)}")
    print(f"wrote {H_OUT.relative_to(ROOT)}")
    print(f"wrote {PY_OUT.relative_to(ROOT)}")
    print(f"\n{len(spec['features'])} features, "
          f"{len(spec['teaching_action_rules'])} teaching rules, "
          f"{len(spec['confidence_rules'])} confidence rules")
    print("\nNow run: python3 tools/test_parity.py")


if __name__ == "__main__":
    main()
