#!/usr/bin/env python3
"""Generate firmware/braille_tutor/braille_map.h from data/braille_map.json.

The ESP32 stores each character as a single 6-bit mask, not an image:
bit 0 = dot 1 ... bit 5 = dot 6. That is the whole reason the Braille data lives
as dot arrays instead of pictures -- one byte per character drives both the
vibration motors and the answer comparison.

    python3 tools/gen_braille_header.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP_PATH = ROOT / "data" / "braille_map.json"
OUT = ROOT / "firmware" / "braille_tutor" / "braille_map.h"


def dots_to_mask(dots):
    m = 0
    for d in dots:
        m |= 1 << (d - 1)
    return m


def main():
    data = json.loads(MAP_PATH.read_text(encoding="utf-8"))
    letters = data["letters"]

    rows, names, romans = [], [], []
    for l in letters:
        mask = dots_to_mask(l["dots"])
        dot_str = "-".join(str(d) for d in l["dots"])
        rows.append(f"  0x{mask:02X},  // {l['id']:>2}  {l['char']}  {l['name']:<14} dots {dot_str}")
        names.append(f'  "{l["name"]}"')
        romans.append(f'  "{l["roman"]}"')

    n = len(letters)
    verified = "1" if data["verified"] else "0"
    warn = "" if data["verified"] else (
        "\n// !! GENERATED FROM AN UNVERIFIED PLACEHOLDER MAPPING.\n"
        "// !! Swap in the verified Bangladesh chart before real learners use this.\n"
    )

    header = f"""// GENERATED by tools/gen_braille_header.py from data/braille_map.json -- DO NOT EDIT
// standard: {data['standard']}   verified: {data['verified']}{warn}
#ifndef BRAILLE_MAP_H
#define BRAILLE_MAP_H

#include <stdint.h>

#define BRAILLE_LETTER_COUNT {n}
#define BRAILLE_MAP_VERIFIED {verified}
#define BRAILLE_VOWEL_COUNT {sum(1 for l in letters if l['category'] == 'vowel')}

// Bit i set => dot i+1 is raised.  bit0=dot1 bit1=dot2 bit2=dot3
//                                  bit3=dot4 bit4=dot5 bit5=dot6
// Index is the letter id, which matches feature 0 (char_id) exactly.
static const uint8_t BRAILLE_PATTERN[BRAILLE_LETTER_COUNT] = {{
{chr(10).join(rows)}
}};

// Kept in PROGMEM-free plain flash; only used for SD-card log lines.
static const char *const BRAILLE_NAME[BRAILLE_LETTER_COUNT] = {{
{("," + chr(10)).join(names)}
}};

static const char *const BRAILLE_ROMAN[BRAILLE_LETTER_COUNT] = {{
{("," + chr(10)).join(romans)}
}};

// DFPlayer track number for letter id (files are /mp3/0001.mp3 .. /mp3/{n:04d}.mp3)
static inline uint16_t braille_track(uint8_t letter_id) {{
  return (uint16_t)letter_id + 1;
}}

static inline uint8_t braille_dot_count(uint8_t mask) {{
  uint8_t c = 0;
  for (uint8_t i = 0; i < 6; i++) if (mask & (1 << i)) c++;
  return c;
}}

#endif  // BRAILLE_MAP_H
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({n} letters)")
    if not data["verified"]:
        print("\n  !! generated from the UNVERIFIED placeholder mapping")


if __name__ == "__main__":
    main()
