# GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT
# spec version: 2
"""Python mirror of the rule engine. Imported by gen_synthetic.py and train.py."""
from enum import IntEnum

SPEC_VERSION = 2


class TeachingAction(IntEnum):
    REPEAT = 0
    HINT = 1
    NORMAL_PRACTICE = 2


class ConfidenceState(IntEnum):
    CONFIDENT = 0
    HESITANT = 1
    GUESSING = 2


TEACHING_ACTION_NAMES = ["REPEAT", "HINT", "NORMAL_PRACTICE"]
CONFIDENCE_STATE_NAMES = ["CONFIDENT", "HESITANT", "GUESSING"]

# All 14 sampled/logged features, in spec order -- the CSV/DB column
# list. Use this for logging (export_dataset.py, gen_synthetic.py), NOT for
# building the model input vector.
ALL_FEATURE_NAMES = ["char_id", "response_time", "press_duration", "retry_count", "prev_accuracy", "prev_mastery", "hint_count", "session_number", "difficulty_level", "time_since_last_practice", "prev_confidence", "current_streak", "wrong_streak", "prev_mistakes"]
# (name, min, max) for ALL 14 logged features -- use this (not the
# model-only FEATURE_RANGES below) to look up a specific feature's raw range
# regardless of whether it feeds the model, e.g. the "never practiced"
# sentinel for time_since_last_practice.
ALL_FEATURE_RANGES = [
    ('char_id', 0.0, 49.0),
    ('response_time', 0.0, 15000.0),
    ('press_duration', 0.0, 2000.0),
    ('retry_count', 0.0, 10.0),
    ('prev_accuracy', 0.0, 1.0),
    ('prev_mastery', 0.0, 1.0),
    ('hint_count', 0.0, 10.0),
    ('session_number', 1.0, 50.0),
    ('difficulty_level', 1.0, 5.0),
    ('time_since_last_practice', 0.0, 604800.0),
    ('prev_confidence', 0.0, 2.0),
    ('current_streak', 0.0, 20.0),
    ('wrong_streak', 0.0, 20.0),
    ('prev_mistakes', 0.0, 50.0),
]

# (index, name, min, max) in canonical MODEL INPUT order -- only features with
# model_input=true in the spec.
FEATURE_RANGES = [
    (0, 'response_time', 0.0, 15000.0),
    (1, 'press_duration', 0.0, 2000.0),
    (2, 'retry_count', 0.0, 10.0),
    (3, 'wrong_streak', 0.0, 20.0),
]
FEATURE_NAMES = [r[1] for r in FEATURE_RANGES]
FEATURE_COUNT = 4


def normalize_features(f):
    """Fixed min-max scaling with clamping. Ranges are from the spec, not the
    dataset, so retraining can never desync this from the deployed model."""
    out = []
    for _, name, lo, hi in FEATURE_RANGES:
        v = (float(f[name]) - lo) / (hi - lo)
        out.append(0.0 if v < 0.0 else 1.0 if v > 1.0 else v)
    return out


def feature_vector(f):
    return [float(f[name]) for _, name, _, _ in FEATURE_RANGES]


def evaluate_teaching_action(f):
    # ta_repeat_on_first_wrong: First wrong attempt on this prompt -- just try again, no help yet.
    if f['wrong_streak'] >= 1.0 and f['retry_count'] == 0.0: return TeachingAction.REPEAT

    # ta_hint_while_stuck: Still wrong after at least one retry on this prompt (retry_count>=1, since ta_repeat_on_first_wrong already caught retry_count==0). Keep helping on THIS character every subsequent wrong try, uncapped, rather than escalating to a different one -- REVIEW_PREVIOUS was removed because abandoning the current letter mid-struggle teaches nothing about the letter the learner actually needs.
    if f['wrong_streak'] >= 1.0: return TeachingAction.HINT

    # ta_default: wrong_streak==0, so the attempt just scored was correct -- move on normally.
    return TeachingAction.NORMAL_PRACTICE


def evaluate_confidence(f):
    # cs_guessing: Many retries or a very long pause both read as guessing.
    if f['retry_count'] >= 2.0 or f['response_time'] >= 6000.0: return ConfidenceState.GUESSING

    # cs_confident: Fast, clean, first-try, correct.
    if f['response_time'] <= 2500.0 and f['retry_count'] == 0.0 and f['wrong_streak'] == 0.0 and f['press_duration'] <= 400.0: return ConfidenceState.CONFIDENT

    # cs_default: Default.
    return ConfidenceState.HESITANT


def update_mastery(mastery, correct):
    return (mastery + 0.25 * (1.0 - mastery)) if correct \
        else (mastery - 0.35 * mastery)


MASTERY_INITIAL = 0.0
SESSION_IDLE_TIMEOUT_S = 900
SESSION_TARGET_ATTEMPTS = 20
