# GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT
# spec version: 1
"""Python mirror of the rule engine. Imported by gen_synthetic.py and train.py."""
from enum import IntEnum

SPEC_VERSION = 1


class TeachingAction(IntEnum):
    REPEAT = 0
    HINT = 1
    NORMAL_PRACTICE = 2
    INCREASE_DIFFICULTY = 3
    REVIEW_PREVIOUS = 4
    WORD_PRACTICE = 5


class ConfidenceState(IntEnum):
    CONFIDENT = 0
    HESITANT = 1
    GUESSING = 2


TEACHING_ACTION_NAMES = ["REPEAT", "HINT", "NORMAL_PRACTICE", "INCREASE_DIFFICULTY", "REVIEW_PREVIOUS", "WORD_PRACTICE"]
CONFIDENCE_STATE_NAMES = ["CONFIDENT", "HESITANT", "GUESSING"]

# (index, name, min, max) in canonical model-input order
FEATURE_RANGES = [
    (0, 'char_id', 0.0, 49.0),
    (1, 'response_time', 0.0, 15000.0),
    (2, 'press_duration', 0.0, 2000.0),
    (3, 'retry_count', 0.0, 10.0),
    (4, 'prev_accuracy', 0.0, 1.0),
    (5, 'prev_mastery', 0.0, 1.0),
    (6, 'hint_count', 0.0, 10.0),
    (7, 'session_number', 1.0, 50.0),
    (8, 'difficulty_level', 1.0, 5.0),
    (9, 'time_since_last_practice', 0.0, 604800.0),
    (10, 'prev_confidence', 0.0, 2.0),
    (11, 'current_streak', 0.0, 20.0),
    (12, 'wrong_streak', 0.0, 20.0),
    (13, 'prev_mistakes', 0.0, 50.0),
]
FEATURE_NAMES = [r[1] for r in FEATURE_RANGES]
FEATURE_COUNT = 14


def normalize_features(f):
    """Fixed min-max scaling with clamping. Ranges are from the spec, not the
    dataset, so retraining can never desync this from the deployed model."""
    out = []
    for _, name, lo, hi in FEATURE_RANGES:
        v = (float(f[name]) - lo) / (hi - lo)
        out.append(0.0 if v < 0.0 else 1.0 if v > 1.0 else v)
    return out


def feature_vector(f):
    return [float(f[name]) for _, name, _, _ in FEATURE_RANGES]


def evaluate_teaching_action(f):
    # ta_review_on_repeated_failure: Three wrong in a row on one character means the learner is stuck go back rather than grind.
    if f['wrong_streak'] >= 3.0: return TeachingAction.REVIEW_PREVIOUS

    # ta_hint_after_retries: Struggling but no hint given yet.
    if f['retry_count'] >= 2.0 and f['hint_count'] == 0.0: return TeachingAction.HINT

    # ta_repeat_on_wrong: Attempt was wrong (see correctness_is_derivable) but not yet stuck.
    if f['wrong_streak'] >= 1.0: return TeachingAction.REPEAT

    # ta_word_practice_on_mastery: Character is solid move to word-level use.
    if f['prev_mastery'] >= 0.85 and f['current_streak'] >= 5.0 and f['prev_accuracy'] >= 0.8: return TeachingAction.WORD_PRACTICE

    # ta_increase_difficulty: Doing well raise the tier.
    if f['prev_mastery'] >= 0.7 and f['current_streak'] >= 3.0: return TeachingAction.INCREASE_DIFFICULTY

    # ta_review_after_long_gap: Character was partly learned, then went stale for a day and faded. The prev_mastery >= 0.05 floor is load-bearing: a never-before-seen character reports maximum time_since_last_practice (the 'never practiced' sentinel) with mastery 0, and without the floor this rule fires on first sight of EVERY character -- which is nonsense, you cannot review something never learned. It also excludes characters the learner has only ever failed (mastery stays exactly 0), which need NORMAL_PRACTICE, not review.
    if f['prev_mastery'] >= 0.05 and f['time_since_last_practice'] >= 86400.0 and f['prev_mastery'] < 0.5: return TeachingAction.REVIEW_PREVIOUS

    # ta_default: Default.
    return TeachingAction.NORMAL_PRACTICE


def evaluate_confidence(f):
    # cs_guessing: Many retries or a very long pause both read as guessing.
    if f['retry_count'] >= 2.0 or f['response_time'] >= 6000.0: return ConfidenceState.GUESSING

    # cs_confident: Fast, clean, first-try, correct.
    if f['response_time'] <= 2500.0 and f['retry_count'] == 0.0 and f['wrong_streak'] == 0.0 and f['press_duration'] <= 400.0: return ConfidenceState.CONFIDENT

    # cs_default: Default.
    return ConfidenceState.HESITANT


def update_mastery(mastery, correct):
    return (mastery + 0.25 * (1.0 - mastery)) if correct \
        else (mastery - 0.35 * mastery)


MASTERY_INITIAL = 0.0
SESSION_IDLE_TIMEOUT_S = 900
SESSION_TARGET_ATTEMPTS = 20
