#!/usr/bin/env python3
"""Convert models/model.tflite into a C header the ESP32 sketch compiles in.

    python3 tools/tflite_to_header.py

Emits firmware/braille_tutor/model_data.h containing:
  - the .tflite flatbuffer as a 16-byte-aligned uint8 array
  - the input/output quantization constants, copied straight from the flatbuffer
    so the firmware never hand-codes a scale or zero point
  - the golden vectors from training, so the sketch can prove on boot that it
    computes what train.py computed

The alignment attribute is not decoration: TFLite Micro requires the model
buffer to be aligned, and an unaligned array produces a load failure at
runtime that is easy to misread as a corrupt model.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import rule_engine_gen as engine  # noqa: E402

TFLITE = ROOT / "models" / "model.tflite"
GOLDEN = ROOT / "models" / "golden_vectors.json"
METRICS = ROOT / "models" / "metrics.json"
OUT = ROOT / "firmware" / "braille_tutor" / "model_data.h"


def main():
    if not TFLITE.exists():
        sys.exit(f"{TFLITE.relative_to(ROOT)} not found -- run tools/train.py first")

    blob = TFLITE.read_bytes()

    # read quantization straight from the model rather than trusting a note
    import tensorflow as tf
    interp = tf.lite.Interpreter(model_content=blob)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    outs = interp.get_output_details()
    in_scale, in_zp = inp["quantization"]

    heads = {}
    for d in outs:
        n = int(d["shape"][-1])
        s, z = d["quantization"]
        heads[n] = (s, z, int(d["index"]))
    n_cs = len(engine.CONFIDENCE_STATE_NAMES)
    n_ta = len(engine.TEACHING_ACTION_NAMES)
    if n_cs not in heads or n_ta not in heads:
        sys.exit(f"model outputs {sorted(heads)} do not match heads {n_cs}/{n_ta}")

    golden = json.loads(GOLDEN.read_text(encoding="utf-8")) if GOLDEN.exists() else {"vectors": []}
    metrics = json.loads(METRICS.read_text(encoding="utf-8")) if METRICS.exists() else {}
    vectors = golden.get("vectors", [])[:12]

    # byte array
    rows = []
    for i in range(0, len(blob), 12):
        rows.append("  " + " ".join(f"0x{b:02x}," for b in blob[i:i + 12]))
    byte_block = "\n".join(rows)

    # golden vectors
    g_lines = []
    for v in vectors:
        norm = ", ".join(f"{x:.8f}f" for x in v["features_norm"])
        g_lines.append(f"  {{ {{ {norm} }}, {v['expect_teaching']}, {v['expect_confidence']} }},")
    g_block = "\n".join(g_lines) if g_lines else "  // (none -- train.py wrote no golden vectors)"

    trained_real = metrics.get("trained_on_real_data", None)
    warn = ""
    if trained_real is False:
        warn = ("\n// !! This model was trained on SYNTHETIC DATA ONLY. Its accuracy numbers\n"
                "// !! are circular and say nothing about real learners. Pipeline test only.\n")

    header = f"""// GENERATED by tools/tflite_to_header.py -- DO NOT EDIT
// source: models/model.tflite ({len(blob)} bytes)
// spec version: {engine.SPEC_VERSION}{warn}
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

// TFLite Micro requires an aligned model buffer. Without the alignas the
// interpreter fails to load with an error that looks like model corruption.
#define MODEL_DATA_LEN {len(blob)}
alignas(16) static const unsigned char MODEL_DATA[MODEL_DATA_LEN] = {{
{byte_block}
}};

// Quantization constants read out of the flatbuffer itself, never hand-copied.
// The firmware quantizes with:  q = round(x / scale) + zero_point
#define MODEL_INPUT_SCALE       {in_scale:.10f}f
#define MODEL_INPUT_ZERO_POINT  {int(in_zp)}
#define MODEL_CONF_SCALE        {heads[n_cs][0]:.10f}f
#define MODEL_CONF_ZERO_POINT   {int(heads[n_cs][1])}
#define MODEL_TEACH_SCALE       {heads[n_ta][0]:.10f}f
#define MODEL_TEACH_ZERO_POINT  {int(heads[n_ta][1])}

#define MODEL_CONF_CLASSES  {n_cs}
#define MODEL_TEACH_CLASSES {n_ta}

// Tensor arena. The model is ~{len(blob) // 1024} KB with two small dense layers, so this is
// generous; the sketch prints the actually-used size at boot so you can shrink it.
#define MODEL_ARENA_SIZE (8 * 1024)

// Golden vectors captured during training. firmware replays these on boot: if
// any one mismatches, the ESP32 is not computing what train.py computed, and
// nothing downstream of that is trustworthy.
typedef struct {{
  float features_norm[{engine.FEATURE_COUNT}];
  int8_t expect_teaching;
  int8_t expect_confidence;
}} GoldenVector;

#define GOLDEN_VECTOR_COUNT {len(vectors)}
static const GoldenVector GOLDEN_VECTORS[] = {{
{g_block}
}};

#endif  // MODEL_DATA_H
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  model bytes    : {len(blob)} ({len(blob) / 1024:.1f} KB)")
    print(f"  input quant    : scale {in_scale:.8f}  zero_point {int(in_zp)}")
    print(f"  golden vectors : {len(vectors)}")
    if trained_real is False:
        print("\n  !! model trained on synthetic data only -- not a real-learner model")
    return 0


if __name__ == "__main__":
    sys.exit(main())
