#!/usr/bin/env python3
"""Train the multi-task model and export an int8 TFLite file for the ESP32.

    python3 tools/train.py --real dataset/real.csv --synthetic dataset/synthetic.csv

Architecture (from the project docs):
    Input(14) -> Dense(32,relu) -> Dense(16,relu) -> [Dense(3,softmax), Dense(6,softmax)]

What this script reports, and why each number is here:

  * REAL-ONLY test accuracy, separate from combined. This is the number that
    means something. Synthetic rows are generated by simulating learners and
    labelled by the same rule engine, so a model scoring 99% on them has mostly
    proved it can imitate a function it was handed. Real held-out rows are the
    only evidence about real behaviour.

  * Rule-engine agreement rate, stated plainly. The labels come FROM the rule
    engine, so high agreement is the expected result, not a discovery. Report
    this as "the network learned to compress the rule engine into 1.2k
    parameters", which is a legitimate TinyML result, and do not describe it as
    autonomous policy learning.

  * Disagreement cases on held-out REAL data, dumped to disk. These are the only
    rows where the model does something the rule engine did not. Read them.

  * Majority-class baseline next to model accuracy. Without it, "94% accurate"
    is unreadable when one class holds 60% of the rows.

  * TFLite-vs-Keras agreement after quantization. int8 quantization changes
    outputs; if this drops, the model you deploy is not the model you validated.
"""
import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import rule_engine_gen as engine  # noqa: E402

N_TA = len(engine.TEACHING_ACTION_NAMES)
N_CS = len(engine.CONFIDENCE_STATE_NAMES)


def norm_bool(v):
    return str(v).strip().lower() in ("true", "t", "1", "yes")


def load_csv(path):
    if not path or not Path(path).exists():
        return []
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def to_arrays(rows):
    """Normalized features + both label heads. Normalization comes from the
    generated engine, so it is bit-identical to what the ESP32 computes."""
    X = np.zeros((len(rows), engine.FEATURE_COUNT), dtype=np.float32)
    y_ta = np.zeros(len(rows), dtype=np.int32)
    y_cs = np.zeros(len(rows), dtype=np.int32)
    for i, r in enumerate(rows):
        f = {name: float(r[name]) for name in engine.FEATURE_NAMES}
        X[i] = engine.normalize_features(f)
        y_ta[i] = int(float(r["teaching_action"]))
        y_cs[i] = int(float(r["confidence_state"]))
    return X, y_ta, y_cs


def stratified_split(y, seed, train=0.70, val=0.15):
    """Split per class so rare classes appear in all three sets."""
    rng = np.random.default_rng(seed)
    idx_tr, idx_va, idx_te = [], [], []
    for c in np.unique(y):
        idx = np.where(y == c)[0]
        rng.shuffle(idx)
        n = len(idx)
        n_tr = max(1, int(round(n * train)))
        n_va = max(1, int(round(n * val))) if n >= 3 else 0
        if n_tr + n_va >= n:
            n_tr, n_va = max(1, n - 2), 1 if n >= 3 else 0
        idx_tr += list(idx[:n_tr])
        idx_va += list(idx[n_tr:n_tr + n_va])
        idx_te += list(idx[n_tr + n_va:])
    rng.shuffle(idx_tr); rng.shuffle(idx_va); rng.shuffle(idx_te)
    return np.array(idx_tr), np.array(idx_va), np.array(idx_te)


def confusion(y_true, y_pred, names):
    n = len(names)
    m = np.zeros((n, n), dtype=int)
    for t, p in zip(y_true, y_pred):
        m[t, p] += 1
    w = max(len(x) for x in names) + 1
    lines = [" " * w + "".join(f"{i:>6}" for i in range(n)) + "   <- predicted"]
    for i, name in enumerate(names):
        lines.append(f"{name:<{w}}" + "".join(f"{m[i, j]:>6}" for j in range(n)))
    return "\n".join(lines)


def per_class_report(y_true, y_pred, names):
    lines = [f"  {'class':<22}{'n':>6}{'recall':>9}{'precision':>11}"]
    for i, name in enumerate(names):
        tp = int(np.sum((y_true == i) & (y_pred == i)))
        actual = int(np.sum(y_true == i))
        predicted = int(np.sum(y_pred == i))
        rec = tp / actual if actual else float("nan")
        prec = tp / predicted if predicted else float("nan")
        lines.append(f"  {name:<22}{actual:>6}{rec:>9.3f}{prec:>11.3f}")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--real", type=Path, default=ROOT / "dataset" / "real.csv")
    ap.add_argument("--synthetic", type=Path, default=ROOT / "dataset" / "synthetic.csv")
    ap.add_argument("--out", type=Path, default=ROOT / "models")
    ap.add_argument("--epochs", type=int, default=250)
    ap.add_argument("--batch", type=int, default=32)
    ap.add_argument("--seed", type=int, default=20260730)
    ap.add_argument("--allow-no-real", action="store_true",
                    help="train without any real rows (pipeline smoke test only)")
    args = ap.parse_args()

    import tensorflow as tf
    tf.random.set_seed(args.seed)
    np.random.seed(args.seed)

    real_rows = [r for r in load_csv(args.real) if not norm_bool(r["is_synthetic"])]
    synth_rows = [r for r in load_csv(args.synthetic) if norm_bool(r["is_synthetic"])]

    print("=" * 68)
    print(f"real rows      : {len(real_rows)}")
    print(f"synthetic rows : {len(synth_rows)}")
    if real_rows or synth_rows:
        share = 100 * len(real_rows) / (len(real_rows) + len(synth_rows))
        print(f"real share     : {share:.0f}%")

    if not real_rows and not args.allow_no_real:
        sys.exit(
            "\nNo real rows found.\n"
            "Training only on synthetic data measures nothing: the rows were\n"
            "simulated and labelled by the same rule engine the model is being\n"
            "asked to reproduce, so accuracy is circular. Collect real sessions\n"
            "first, regenerate synthetic data fitted to them, then train.\n"
            "Pass --allow-no-real to smoke-test the pipeline anyway.")
    if not real_rows:
        print("\n!! --allow-no-real: SYNTHETIC ONLY. Every accuracy number below is")
        print("!! circular and means nothing about real learners. Pipeline test only.")

    all_rows = real_rows + synth_rows
    is_real = np.array([True] * len(real_rows) + [False] * len(synth_rows))
    X, y_ta, y_cs = to_arrays(all_rows)

    # Split stratified on the teaching head (6 classes, the harder one).
    i_tr, i_va, i_te = stratified_split(y_ta, args.seed)
    print(f"\nsplit          : train {len(i_tr)} / val {len(i_va)} / test {len(i_te)}")
    print(f"real in test   : {int(np.sum(is_real[i_te]))}")

    # --- model ------------------------------------------------------------
    inp = tf.keras.Input(shape=(engine.FEATURE_COUNT,), name="features")
    h = tf.keras.layers.Dense(32, activation="relu", name="dense_32")(inp)
    h = tf.keras.layers.Dense(16, activation="relu", name="dense_16")(h)
    out_cs = tf.keras.layers.Dense(N_CS, activation="softmax", name="confidence")(h)
    out_ta = tf.keras.layers.Dense(N_TA, activation="softmax", name="teaching")(h)
    model = tf.keras.Model(inp, [out_cs, out_ta])

    # Class balancing is folded into the loss rather than passed as
    # class_weight/sample_weight: Keras 3 rejects both forms on a multi-output
    # model. Without it the rare teaching actions get ignored in favour of the
    # majority class, which reads as good accuracy and is useless.
    def balanced_weights(y, n_classes):
        cnt = Counter(y.tolist())
        total = sum(cnt.values())
        return np.array([total / (n_classes * cnt[c]) if cnt.get(c) else 1.0
                         for c in range(n_classes)], dtype=np.float32)

    def weighted_scce(class_w):
        w = tf.constant(class_w)

        def loss_fn(y_true, y_pred):
            y = tf.cast(tf.reshape(y_true, [-1]), tf.int32)
            base = tf.keras.losses.sparse_categorical_crossentropy(y, y_pred)
            return base * tf.gather(w, y)
        return loss_fn

    w_ta = balanced_weights(y_ta[i_tr], N_TA)
    w_cs = balanced_weights(y_cs[i_tr], N_CS)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(1e-3),
        loss={"confidence": weighted_scce(w_cs), "teaching": weighted_scce(w_ta)},
        loss_weights={"confidence": 1.0, "teaching": 1.0},
        metrics={"confidence": "accuracy", "teaching": "accuracy"},
    )
    print(f"\ntrainable params: {model.count_params()}")
    print("class weights (teaching): " +
          ", ".join(f"{n}={v:.2f}" for n, v in
                    zip(engine.TEACHING_ACTION_NAMES, w_ta)))

    hist = model.fit(
        X[i_tr], {"confidence": y_cs[i_tr], "teaching": y_ta[i_tr]},
        validation_data=(X[i_va], {"confidence": y_cs[i_va], "teaching": y_ta[i_va]}),
        epochs=args.epochs, batch_size=args.batch, verbose=0,
        callbacks=[
            tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=40,
                                             restore_best_weights=True),
            tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                                                 patience=18, min_lr=1e-5),
        ],
    )
    print(f"epochs run     : {len(hist.history['loss'])}")

    # --- evaluation --------------------------------------------------------
    p_cs, p_ta = model.predict(X[i_te], verbose=0)
    pred_cs, pred_ta = p_cs.argmax(1), p_ta.argmax(1)
    true_cs, true_ta = y_cs[i_te], y_ta[i_te]

    def acc(t, p):
        return float(np.mean(t == p)) if len(t) else float("nan")

    real_mask = is_real[i_te]
    maj_ta = Counter(y_ta[i_tr].tolist()).most_common(1)[0]
    maj_cs = Counter(y_cs[i_tr].tolist()).most_common(1)[0]
    base_ta = float(np.mean(true_ta == maj_ta[0]))
    base_cs = float(np.mean(true_cs == maj_cs[0]))

    print("\n" + "=" * 68)
    print("TEST RESULTS")
    print("=" * 68)
    print(f"{'':<26}{'combined':>12}{'REAL only':>12}{'majority':>12}")
    print(f"{'teaching action acc':<26}{acc(true_ta, pred_ta):>12.4f}"
          f"{acc(true_ta[real_mask], pred_ta[real_mask]):>12.4f}{base_ta:>12.4f}")
    print(f"{'confidence state acc':<26}{acc(true_cs, pred_cs):>12.4f}"
          f"{acc(true_cs[real_mask], pred_cs[real_mask]):>12.4f}{base_cs:>12.4f}")
    print("\n'majority' is the accuracy of always predicting the most common training")
    print("class. A model only just above it has learned almost nothing.")

    print("\nteaching action, per class:")
    print(per_class_report(true_ta, pred_ta, engine.TEACHING_ACTION_NAMES))
    print("\nconfidence state, per class:")
    print(per_class_report(true_cs, pred_cs, engine.CONFIDENCE_STATE_NAMES))
    print("\nteaching action confusion matrix:")
    print(confusion(true_ta, pred_ta, engine.TEACHING_ACTION_NAMES))

    # --- rule-engine agreement + disagreement dump -------------------------
    test_rows = [all_rows[i] for i in i_te]
    agree_ta = int(np.sum(pred_ta == true_ta))
    print("\n" + "=" * 68)
    print("RULE-ENGINE AGREEMENT")
    print("=" * 68)
    print(f"teaching action : {agree_ta}/{len(true_ta)} = {agree_ta / len(true_ta):.4f}")
    print("\nThe labels ARE the rule engine's output, so high agreement is the")
    print("expected result and not evidence of learned teaching policy. The")
    print("honest framing: the network compressed the rule engine into")
    print(f"{model.count_params()} parameters that run offline on an ESP32.")

    disagree = [(k, test_rows[k]) for k in range(len(true_ta)) if pred_ta[k] != true_ta[k]]
    real_disagree = [(k, r) for k, r in disagree if real_mask[k]]
    dump = args.out / "disagreements.csv"
    args.out.mkdir(parents=True, exist_ok=True)
    if disagree:
        with open(dump, "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(["is_real", "rule_label", "model_label", "model_confidence",
                        *engine.FEATURE_NAMES])
            for k, r in disagree:
                w.writerow([
                    bool(real_mask[k]),
                    engine.TEACHING_ACTION_NAMES[true_ta[k]],
                    engine.TEACHING_ACTION_NAMES[pred_ta[k]],
                    f"{p_ta[k].max():.3f}",
                    *[r[n] for n in engine.FEATURE_NAMES],
                ])
    print(f"\ndisagreements   : {len(disagree)} total, {len(real_disagree)} on REAL rows")
    print(f"written to      : {dump.relative_to(ROOT)}")
    print("Read the real ones. They are the only rows where the model departs")
    print("from the rule engine, and the only material for claiming it learned")
    print("anything beyond imitation.")

    # --- TFLite int8 -------------------------------------------------------
    print("\n" + "=" * 68)
    print("TFLITE CONVERSION")
    print("=" * 68)

    def rep_data():
        idx = i_tr[:min(500, len(i_tr))]
        for i in idx:
            yield [X[i:i + 1].astype(np.float32)]

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep_data
    # Full-integer quantization: TFLite Micro on ESP32 has no float kernels
    # worth using, and int8 makes inference deterministic across the toolchain.
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    tflite_model = conv.convert()

    tfl_path = args.out / "model.tflite"
    tfl_path.write_bytes(tflite_model)
    print(f"model.tflite    : {len(tflite_model)} bytes ({len(tflite_model) / 1024:.1f} KB)")

    # --- verify the quantized model still agrees with the float one --------
    interp = tf.lite.Interpreter(model_content=tflite_model)
    interp.allocate_tensors()
    in_det = interp.get_input_details()[0]
    out_dets = interp.get_output_details()
    in_scale, in_zp = in_det["quantization"]

    q_preds = {d["index"]: [] for d in out_dets}
    for i in i_te:
        q = np.clip(np.round(X[i] / in_scale + in_zp), -128, 127).astype(np.int8)
        interp.set_tensor(in_det["index"], q.reshape(1, -1))
        interp.invoke()
        for d in out_dets:
            q_preds[d["index"]].append(int(np.argmax(interp.get_tensor(d["index"])[0])))

    # match each tflite output to a head by size
    by_size = {}
    for d in out_dets:
        by_size[int(d["shape"][-1])] = np.array(q_preds[d["index"]])
    tfl_cs = by_size.get(N_CS)
    tfl_ta = by_size.get(N_TA)

    print(f"tflite vs keras : teaching {np.mean(tfl_ta == pred_ta):.4f} agreement, "
          f"confidence {np.mean(tfl_cs == pred_cs):.4f}")
    print(f"tflite test acc : teaching {acc(true_ta, tfl_ta):.4f}, "
          f"confidence {acc(true_cs, tfl_cs):.4f}")
    if np.mean(tfl_ta == pred_ta) < 0.97:
        print("\nWARN  int8 quantization shifted predictions by more than 3%.")
        print("      The model you deploy is not quite the one validated above.")

    # --- golden vectors for the firmware -----------------------------------
    # firmware/test_model.ino replays these; a mismatch means the ESP32 is not
    # running the model you trained.
    golden = []
    for k, i in enumerate(i_te[:20]):
        golden.append({
            "features_raw": {n: float(all_rows[i][n]) for n in engine.FEATURE_NAMES},
            "features_norm": [float(v) for v in X[i]],
            "expect_teaching": int(tfl_ta[k]),
            "expect_confidence": int(tfl_cs[k]),
        })
    (args.out / "golden_vectors.json").write_text(
        json.dumps({"quantization": {"input_scale": float(in_scale),
                                     "input_zero_point": int(in_zp)},
                    "vectors": golden}, indent=2), encoding="utf-8")

    model.save(args.out / "model.keras")

    # Python's json writes bare NaN, which is NOT valid JSON -- every other
    # language rejects the file. A metric with no data behind it (real-only
    # accuracy when no real rows were collected) is genuinely absent, so it is
    # written as null rather than as a number that is not a number.
    def clean(v):
        return None if isinstance(v, float) and (v != v or v in (float("inf"), float("-inf"))) else v

    (args.out / "metrics.json").write_text(json.dumps({
        "params": int(model.count_params()),
        "rows": {"real": len(real_rows), "synthetic": len(synth_rows)},
        "test": {
            "teaching_combined": clean(acc(true_ta, pred_ta)),
            "teaching_real_only": clean(acc(true_ta[real_mask], pred_ta[real_mask])),
            "teaching_majority_baseline": clean(base_ta),
            "confidence_combined": clean(acc(true_cs, pred_cs)),
            "confidence_real_only": clean(acc(true_cs[real_mask], pred_cs[real_mask])),
            "confidence_majority_baseline": clean(base_cs),
        },
        "rule_agreement": agree_ta / len(true_ta),
        "disagreements": {"total": len(disagree), "real": len(real_disagree)},
        "tflite_bytes": len(tflite_model),
        "tflite_vs_keras_teaching": float(np.mean(tfl_ta == pred_ta)),
        "spec_version": engine.SPEC_VERSION,
        "trained_on_real_data": bool(real_rows),
    }, indent=2), encoding="utf-8")

    print(f"\nwrote {args.out.relative_to(ROOT)}/: model.tflite, model.keras, "
          "metrics.json, golden_vectors.json, disagreements.csv")
    print("\nNext: python3 tools/tflite_to_header.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
