// GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT
// spec version: 1

export const TEACHING_ACTION = {
  REPEAT: 0,
  HINT: 1,
  NORMAL_PRACTICE: 2,
  INCREASE_DIFFICULTY: 3,
  REVIEW_PREVIOUS: 4,
  WORD_PRACTICE: 5,
};
export const TEACHING_ACTION_NAMES = ["REPEAT", "HINT", "NORMAL_PRACTICE", "INCREASE_DIFFICULTY", "REVIEW_PREVIOUS", "WORD_PRACTICE"];

export const CONFIDENCE_STATE = {
  CONFIDENT: 0,
  HESITANT: 1,
  GUESSING: 2,
};
export const CONFIDENCE_STATE_NAMES = ["CONFIDENT", "HESITANT", "GUESSING"];

// Canonical feature order. The model input vector MUST be built in this order.
export const FEATURE_INDEX = {
  char_id: 0,
  response_time: 1,
  press_duration: 2,
  retry_count: 3,
  prev_accuracy: 4,
  prev_mastery: 5,
  hint_count: 6,
  session_number: 7,
  difficulty_level: 8,
  time_since_last_practice: 9,
  prev_confidence: 10,
  current_streak: 11,
  wrong_streak: 12,
  prev_mistakes: 13,
};

export const FEATURE_RANGES = [
  { name: 'char_id', min: 0.0, max: 49.0 },
  { name: 'response_time', min: 0.0, max: 15000.0 },
  { name: 'press_duration', min: 0.0, max: 2000.0 },
  { name: 'retry_count', min: 0.0, max: 10.0 },
  { name: 'prev_accuracy', min: 0.0, max: 1.0 },
  { name: 'prev_mastery', min: 0.0, max: 1.0 },
  { name: 'hint_count', min: 0.0, max: 10.0 },
  { name: 'session_number', min: 1.0, max: 50.0 },
  { name: 'difficulty_level', min: 1.0, max: 5.0 },
  { name: 'time_since_last_practice', min: 0.0, max: 604800.0 },
  { name: 'prev_confidence', min: 0.0, max: 2.0 },
  { name: 'current_streak', min: 0.0, max: 20.0 },
  { name: 'wrong_streak', min: 0.0, max: 20.0 },
  { name: 'prev_mistakes', min: 0.0, max: 50.0 },
];

export const FEATURE_COUNT = 14;

/**
 * Fixed min-max scaling with clamping. Ranges come from the spec, NOT from the
 * dataset, so retraining on more data can never shift what the ESP32 computes.
 */
export function normalizeFeatures(f) {
  const out = new Float32Array(FEATURE_COUNT);
  for (let i = 0; i < FEATURE_COUNT; i++) {
    const r = FEATURE_RANGES[i];
    const raw = f[r.name];
    if (raw === undefined || raw === null || Number.isNaN(raw)) {
      throw new Error('normalizeFeatures: missing feature ' + r.name);
    }
    let v = (raw - r.min) / (r.max - r.min);
    if (v < 0) v = 0;
    if (v > 1) v = 1;
    out[i] = v;
  }
  return out;
}

/** Ordered raw feature vector, for CSV logging. */
export function featureVector(f) {
  return FEATURE_RANGES.map((r) => f[r.name]);
}

export function evaluateTeachingAction(f) {
  // ta_review_on_repeated_failure: Three wrong in a row on one character means the learner is stuck; go back rather than grind.
  if (f.wrong_streak >= 3.0) return TEACHING_ACTION.REVIEW_PREVIOUS;

  // ta_hint_after_retries: Struggling but no hint given yet.
  if (f.retry_count >= 2.0 && f.hint_count == 0.0) return TEACHING_ACTION.HINT;

  // ta_repeat_on_wrong: Attempt was wrong (see correctness_is_derivable) but not yet stuck.
  if (f.wrong_streak >= 1.0) return TEACHING_ACTION.REPEAT;

  // ta_word_practice_on_mastery: Character is solid; move to word-level use.
  if (f.prev_mastery >= 0.85 && f.current_streak >= 5.0 && f.prev_accuracy >= 0.8) return TEACHING_ACTION.WORD_PRACTICE;

  // ta_increase_difficulty: Doing well; raise the tier.
  if (f.prev_mastery >= 0.7 && f.current_streak >= 3.0) return TEACHING_ACTION.INCREASE_DIFFICULTY;

  // ta_review_after_long_gap: Weak character not seen for a day; refresh it.
  if (f.time_since_last_practice >= 86400.0 && f.prev_mastery < 0.5) return TEACHING_ACTION.REVIEW_PREVIOUS;

  // ta_default: Default.
  return TEACHING_ACTION.NORMAL_PRACTICE;
}

export function evaluateConfidence(f) {
  // cs_guessing: Many retries or a very long pause both read as guessing.
  if (f.retry_count >= 2.0 || f.response_time >= 6000.0) return CONFIDENCE_STATE.GUESSING;

  // cs_confident: Fast, clean, first-try, correct.
  if (f.response_time <= 2500.0 && f.retry_count == 0.0 && f.wrong_streak == 0.0 && f.press_duration <= 400.0) return CONFIDENCE_STATE.CONFIDENT;

  // cs_default: Default.
  return CONFIDENCE_STATE.HESITANT;
}

/** EMA mastery update. Must match firmware and gen_synthetic.py exactly. */
export function updateMastery(mastery, correct) {
  return correct
    ? mastery + 0.25 * (1.0 - mastery)
    : mastery - 0.35 * mastery;
}

export const MASTERY_INITIAL = 0.0;
export const SESSION_IDLE_TIMEOUT_S = 900;
export const SESSION_TARGET_ATTEMPTS = 20;
