// GENERATED by tools/gen_engine.py from spec/engine_spec.json -- DO NOT EDIT
// spec version: 2

export const SPEC_VERSION = 2;

export const TEACHING_ACTION = {
  REPEAT: 0,
  HINT: 1,
  NORMAL_PRACTICE: 2,
};
export const TEACHING_ACTION_NAMES = ["REPEAT", "HINT", "NORMAL_PRACTICE"];

export const CONFIDENCE_STATE = {
  CONFIDENT: 0,
  HESITANT: 1,
  GUESSING: 2,
};
export const CONFIDENCE_STATE_NAMES = ["CONFIDENT", "HESITANT", "GUESSING"];

// All 14 sampled/logged features, in spec order. This is the CSV/DB
// column list -- use this for logging, NOT for the model input vector.
export const ALL_FEATURE_NAMES = ["char_id", "response_time", "press_duration", "retry_count", "prev_accuracy", "prev_mastery", "hint_count", "session_number", "difficulty_level", "time_since_last_practice", "prev_confidence", "current_streak", "wrong_streak", "prev_mistakes"];
export const ALL_FEATURE_RANGES = [
  { name: 'char_id', min: 0.0, max: 49.0 },
  { name: 'response_time', min: 0.0, max: 15000.0 },
  { name: 'press_duration', min: 0.0, max: 2000.0 },
  { name: 'retry_count', min: 0.0, max: 10.0 },
  { name: 'prev_accuracy', min: 0.0, max: 1.0 },
  { name: 'prev_mastery', min: 0.0, max: 1.0 },
  { name: 'hint_count', min: 0.0, max: 10.0 },
  { name: 'session_number', min: 1.0, max: 50.0 },
  { name: 'difficulty_level', min: 1.0, max: 5.0 },
  { name: 'time_since_last_practice', min: 0.0, max: 604800.0 },
  { name: 'prev_confidence', min: 0.0, max: 2.0 },
  { name: 'current_streak', min: 0.0, max: 20.0 },
  { name: 'wrong_streak', min: 0.0, max: 20.0 },
  { name: 'prev_mistakes', min: 0.0, max: 50.0 },
];

// Canonical MODEL INPUT order -- only features with model_input=true in the
// spec. The model input vector MUST be built in this order.
export const FEATURE_INDEX = {
  response_time: 0,
  press_duration: 1,
  retry_count: 2,
  wrong_streak: 3,
};

export const FEATURE_RANGES = [
  { name: 'response_time', min: 0.0, max: 15000.0 },
  { name: 'press_duration', min: 0.0, max: 2000.0 },
  { name: 'retry_count', min: 0.0, max: 10.0 },
  { name: 'wrong_streak', min: 0.0, max: 20.0 },
];

export const FEATURE_COUNT = 4;

/**
 * Fixed min-max scaling with clamping. Ranges come from the spec, NOT from the
 * dataset, so retraining on more data can never shift what the ESP32 computes.
 */
export function normalizeFeatures(f) {
  const out = new Float32Array(FEATURE_COUNT);
  for (let i = 0; i < FEATURE_COUNT; i++) {
    const r = FEATURE_RANGES[i];
    const raw = f[r.name];
    if (raw === undefined || raw === null || Number.isNaN(raw)) {
      throw new Error('normalizeFeatures: missing feature ' + r.name);
    }
    let v = (raw - r.min) / (r.max - r.min);
    if (v < 0) v = 0;
    if (v > 1) v = 1;
    out[i] = v;
  }
  return out;
}

/** Ordered raw feature vector, for CSV logging. */
export function featureVector(f) {
  return FEATURE_RANGES.map((r) => f[r.name]);
}

export function evaluateTeachingAction(f) {
  // ta_repeat_on_first_wrong: First wrong attempt on this prompt -- just try again, no help yet.
  if (f.wrong_streak >= 1.0 && f.retry_count == 0.0) return TEACHING_ACTION.REPEAT;

  // ta_hint_while_stuck: Still wrong after at least one retry on this prompt (retry_count>=1, since ta_repeat_on_first_wrong already caught retry_count==0). Keep helping on THIS character every subsequent wrong try, uncapped, rather than escalating to a different one -- REVIEW_PREVIOUS was removed because abandoning the current letter mid-struggle teaches nothing about the letter the learner actually needs.
  if (f.wrong_streak >= 1.0) return TEACHING_ACTION.HINT;

  // ta_default: wrong_streak==0, so the attempt just scored was correct -- move on normally.
  return TEACHING_ACTION.NORMAL_PRACTICE;
}

export function evaluateConfidence(f) {
  // cs_guessing: Many retries or a very long pause both read as guessing.
  if (f.retry_count >= 2.0 || f.response_time >= 6000.0) return CONFIDENCE_STATE.GUESSING;

  // cs_confident: Fast, clean, first-try, correct.
  if (f.response_time <= 2500.0 && f.retry_count == 0.0 && f.wrong_streak == 0.0 && f.press_duration <= 400.0) return CONFIDENCE_STATE.CONFIDENT;

  // cs_default: Default.
  return CONFIDENCE_STATE.HESITANT;
}

/** EMA mastery update. Must match firmware and gen_synthetic.py exactly. */
export function updateMastery(mastery, correct) {
  return correct
    ? mastery + 0.25 * (1.0 - mastery)
    : mastery - 0.35 * mastery;
}

export const MASTERY_INITIAL = 0.0;
export const SESSION_IDLE_TIMEOUT_S = 900;
export const SESSION_TARGET_ATTEMPTS = 20;
